version: "3"

services:
  backend:
    build:
      context: ./blog_backend
      args:
        DJANGO_ALLOWED_HOSTS: "127.0.0.1 localhost"
        DJANGO_SECRET_KEY: "django-insecure-4k4&wkk4!e=ip=*9wp%(&bjx=tw=ax&)t%$w&nbr_cvsxha0c!"
        CORS_ALLOWED_ORIGINS: "http://127.0.0.1:3000 http://localhost:3000"
    command: gunicorn blog_backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    # image: backend:latest
  frontend:
    build:
      context: ./blog_frontend
      args:
        API_URL: "http://127.0.0.1:8000"
    ports:
      - "3000:3000"
    # image: frontend:latest
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder:
